language: "en"

pipeline: "tensorflow_embedding"

"num_hidden_layers_a": 4
"hidden_layer_size_a": [256, 256,128,64]
"num_hidden_layers_b": 0
"hidden_layer_size_b": []
"batch_size": 6
"epochs": 100
# embedding parameters
"embed_dim": 10
"mu_pos": 0.8  # should be 0.0 < ... < 1.0 for 'cosine'
"mu_neg": -0.4  # should be -1.0 < ... < 1.0 for 'cosine'
"similarity_type": "cosine"  # string 'cosine' or 'inner'
"num_neg": 10
"use_max_sim_neg": true  # flag which loss function to use
# regularization
"C2": 0.002
"C_emb": 0.8
"droprate": 0.2
# flag if to tokenize intents
"intent_tokenization_flag": true
"intent_split_symbol": "_"
